--Bài 1
--Câu 8:
alter table SANPHAM 
add constraint SANPHAM_GIA check(gia>500)
--Câu 9
alter table CTHD
add constraint CTHD_SL1 check(SL > 0)
--Câu 10
alter table KHACHHANG
add constraint KHACHHANG_NGDK_NGSINH check(NGDK>NGSINH)

--Bài 2
--Câu 1

--Câu 2
SELECT * FROM SANPHAM,KHACHHANG
--Câu 3
UPDATE SANPHAM SET GIA=GIA+GIA*0.05 WHERE NUOCSX='Thái Lan'
--Câu 4
UPDATE SANPHAM SET GIA =GIA-GIA*0.05 WHERE NUOCSX='TRUNG QUOC' AND GIA >10000
--Câu 5
ALTER TABLE KHACHHANG  ADD LOAIKH TINYINT
UPDATE KHACHHANG SET LOAIKH = 'Vip' WHERE (NGDK<'2007/1/1' AND DOANHSO>=10000000) OR (NGDK>'2007/1/1' AND DOANHSO >=2000000)

--Bài 3
--Câu 1
SELECT MASP,TENSP
FROM  SANPHAM
WHERE NUOCSX='TRUNG QUOC'
--Câu 2
SELECT MASP,TENSP
FROM  SANPHAM
WHERE DVT='CAY' OR DVT='QUYEN'
--Câu 3
SELECT MASP,TENSP
FROM  SANPHAM
WHERE MASP LIKE 'B%01'
--Câu 4
SELECT MASP,TENSP
FROM  SANPHAM
WHERE NUOCSX='TRUNG QUOC' AND GIA BETWEEN 30000 AND 40000
--Câu 5
SELECT MASP,TENSP
FROM  SANPHAM
WHERE (NUOCSX='TRUNG QUOC' OR NUOCSX='THAI LAN') AND GIA BETWEEN 30000 AND 40000
--Câu 6
SELECT SOHD,TRIGIA
FROM  HOADON
WHERE NGHD='1/1/2007' OR NGHD='2/1/2007'
--Câu 7
SELECT SOHD,TRIGIA
FROM  HOADON
WHERE MONTH(NGHD)=1 AND YEAR(NGHD)=2007
ORDER BY  NGHD ASC,TRIGIA DESC
--Câu 8
SELECT A.MAKH,HOTEN
FROM  HOADON A, KHACHHANG B
WHERE A.MAKH=B.MAKH AND NGHD='1/1/2007'
--Câu 9
SELECT SOHD,TRIGIA
FROM  HOADON A, NHANVIEN B
WHERE A.MANV=B.MANV AND NGHD='28/10/2006' AND HOTEN='NGUYEN VAN B' 
--Câu 10
SELECT C.MASP, TENSP
FROM  HOADON A, KHACHHANG B, CTHD C, SANPHAM D
WHERE A.MAKH=B.MAKH AND A.SOHD=C.SOHD AND C.MASP=D.MASP AND
  MONTH(NGHD)=10 AND YEAR(NGHD)=2006 AND HOTEN='NGUYEN VAN A' 


